_wandb:
    value:
        cli_version: 0.27.0
        e:
            eelwdsnja0woc05ypz671czuyh6gyoxn:
                codePath: scripts/train.py
                codePathLocal: scripts/train.py
                cpu_count: 7
                cpu_count_logical: 7
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "209129086976"
                        used: "117149814784"
                email: ulriconava.main@gmail.com
                executable: /python_ml/Projects/marl_air_cargo/.venv/bin/python3
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-42916d82-5838-628e-f02e-29e47b05c80c
                host: vm-ai
                memory:
                    total: "33584529408"
                os: Linux-6.8.0-117-generic-x86_64-with-glibc2.39
                program: /python_ml/Projects/marl_air_cargo/./scripts/train.py
                python: CPython 3.12.3
                root: /python_ml/Projects/marl_air_cargo/mappo_scenario_mo_mlp__7babd072_26_05_19-16_25_01
                startedAt: "2026-05-19T16:25:05.148733Z"
                writerId: eelwdsnja0woc05ypz671czuyh6gyoxn
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 50
            "2":
                - 1
                - 50
            "3":
                - 2
                - 3
                - 13
                - 14
                - 16
            "4": 3.12.3
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
algorithm_config:
    value:
        clip_epsilon: 0.2
        critic_coef: 0.5
        entropy_coef: 0.01
        lmbda: 0.95
        loss_critic_type: l2
        minibatch_advantage: true
        scale_mapping: biased_softplus
        share_param_critic: false
        use_tanh_normal: true
algorithm_name:
    value: mappo
continuous_actions:
    value: false
critic_model_config:
    value:
        _is_critic: true
        activation_class: torch.nn.modules.activation.Tanh
        activation_kwargs: null
        layer_class: torch.nn.modules.linear.Linear
        norm_class: null
        norm_kwargs: null
        num_cells:
            - 128
            - 128
        num_feature_dims: 1
critic_model_name:
    value: mlp
environment_name:
    value: schiphol
experiment_config:
    value:
        adam_eps: 1e-06
        buffer_device: cpu
        checkpoint_at_end: false
        checkpoint_interval: 0
        clip_grad_norm: true
        clip_grad_val: 0.5
        collect_with_grad: false
        create_json: true
        evaluation: true
        evaluation_deterministic_actions: true
        evaluation_episodes: 10
        evaluation_interval: 34560
        evaluation_static: false
        exclude_buffer_from_checkpoint: false
        exploration_anneal_frames: null
        exploration_eps_end: 0.01
        exploration_eps_init: 0.8
        gamma: 0.99
        hard_target_update_frequency: 5
        keep_checkpoints_num: 3
        loggers:
            - csv
            - wandb
        lr: 0.0005
        max_n_frames: 138240
        max_n_iters: null
        off_policy_collected_frames_per_batch: 6000
        off_policy_init_random_frames: 0
        off_policy_memory_size: 1000000
        off_policy_n_envs_per_worker: 10
        off_policy_n_optimizer_steps: 1000
        off_policy_prb_alpha: 0.6
        off_policy_prb_beta: 0.4
        off_policy_train_batch_size: 128
        off_policy_use_prioritized_replay_buffer: false
        on_policy_collected_frames_per_batch: 34560
        on_policy_minibatch_size: 8640
        on_policy_n_envs_per_worker: 1
        on_policy_n_minibatch_iters: 4
        parallel_collection: true
        polyak_tau: 0.005
        prefer_continuous_actions: true
        project_name: benchmarl
        render: true
        restore_file: null
        restore_map_location: null
        sampling_device: cuda
        save_folder: null
        share_policy_params: true
        soft_target_update: true
        train_device: cuda
model_config:
    value:
        _is_critic: false
        activation_class: torch.nn.modules.activation.Tanh
        activation_kwargs: null
        layer_class: torch.nn.modules.linear.Linear
        norm_class: null
        norm_kwargs: null
        num_cells:
            - 128
            - 128
        num_feature_dims: 1
model_name:
    value: mlp
on_policy:
    value: true
seed:
    value: 42
task_config:
    value:
        max_steps: 1440
        with_orchestrator: true
task_name:
    value: scenario_mo
