# =============================================================================
# SIMULATION PARAMETERS CONFIG FILE
# =============================================================================
# DESCRIPTION:
#   This module stores all the parameters of the simulation in a centralized
#   way. Every other module imports this variables from here to allow
#   for centralized management.
# =============================================================================

# =============================================================================
# GHA DOCKS
# =============================================================================
# This section sets the number of dock doors for each gha divided between import and export
ghas:
  dnata:
    total: 50
    import: 25
    export: 25
  klm:
    total: 48
    import: 24
    export: 24
  wfs:
    total: 30
    import: 15
    export: 15
  swiss:
    total: 20
    import: 10
    export: 10

# =============================================================================
# DOCK AVERAGE PROCESSING TIME
# =============================================================================
service_time:
  export: 35
  import: 17

# =============================================================================
# ROAD NETWORK
# =============================================================================
# This section determines the average time it takes to drive a truck from a node to another in the 
# Schiphol perimeter. The "nodes" section binds every node to its name. Example "N3_N4" is the time from 
# klm to wfs.
road:
  segments:
    N0_N1: 2.0
    N0_N2: 2.0
    N0_N3: 1.0
    N0_N4: 3.0
    N0_N5: 5.0
    N1_N2: 0.5
    N1_N3: 2.0
    N1_N4: 4.0
    N1_N5: 6.0
    N2_N3: 2.0
    N2_N4: 4.0
    N2_N5: 6.0
    N3_N4: 2.0
    N3_N5: 4.0
    N4_N5: 2.0
  nodes:
    gate: "N0"
    tp3: "N1"
    dnata: "N2"
    klm: "N3"
    wfs: "N4"
    swiss: "N5"

# =============================================================================
# DEMAND MODEL
# =============================================================================
# This section sets the assumptions for the arrival rate of the trucks.
demand:
  arrival_rate: 0.5    # trucks/minute
  peak_window: [900, 1050]    # in minutes (currently from 15:00 to 17:30)

  # The percentage of the total parcels divided between exp and imp
  flow_split:
    export: 0.60
    import: 0.40

  # This one is tricky, the 4 numbers are the probabilities (expressed in percentage)
  # of a truck doing a multi-stop route. Respectively the probabilities of doing 1, 2, 3 or 4 stops.
  multi_stop_probs: [0.10, 0.30, 0.40, 0.20]

  # This is the percentage of trucks coming from the 4 different origins
  origin_split:
    rfs: 0.25
    nl: 0.35
    forwarder: 0.30
    tp3: 0.10

  # This is the average travel time from each of the 4 origins to the main gate (in minutes)
  # The 2 numbers represent min and max, the system samples randomly inside this range
  origin_travel_time:
    rfs: [15, 90]
    nl: [30, 180]
    forwarder: [20, 100]
    tp3: [0, 2]